In [39]:
import pandas as pd
import numpy as np

In [40]:
df=pd.read_csv(r'C:\Users\M S I\Desktop\5thsem_OJT\project1_diabetes\data\processed\hiba_p1w2_features.csv')

In [41]:
df['outcome'].value_counts()

outcome
0    677
1    273
Name: count, dtype: int64

In [42]:
df.columns

Index(['patient_id', 'age', 'gender', 'pregnancies', 'glucose',
       'blood_pressure', 'skin_thickness', 'insulin', 'bmi',
       'diabetes_pedigree', 'physical_activity', 'smoker', 'last_checkup_date',
       'outcome', 'age_band', 'bmi_category', 'glucose_category',
       'insulin_glucose_ratio', 'pregnancy_rate', 'days_since_checkup',
       'activity_smoker'],
      dtype='str')

In [43]:
feature_cols=['age','pregnancies','glucose','blood_pressure','skin_thickness','insulin','bmi','diabetes_pedigree','bmi_category','glucose_category']

x=df[feature_cols].copy()
y=df['outcome']

In [44]:
x

,age,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,bmi_category,glucose_category
0,79,0,124.000000,71.0,30.0,124.0,23.4,0.588,normal,prediabetic
1,37,0,153.000000,85.0,24.0,42.0,33.9,0.192,obese,diabetes
2,39,0,142.000000,68.0,22.0,159.0,26.9,0.777,overweight,diabetes
3,68,7,121.000000,88.0,26.0,124.0,29.0,1.217,overweight,prediabetic
4,75,0,107.000000,84.0,31.0,101.0,21.2,0.278,normal,prediabetic
...,...,...,...,...,...,...,...,...,...,...
945,64,2,117.855165,81.0,34.0,124.0,40.3,0.641,obese,prediabetic
946,71,0,140.000000,64.0,37.0,124.0,33.4,0.116,obese,diabetes
947,40,0,130.000000,73.0,26.0,258.0,20.1,0.709,normal,diabetes
948,52,4,123.000000,76.0,22.0,189.0,38.9,0.540,obese,prediabetic


In [45]:
y


0      0
1      1
2      0
3      1
4      0
      ..
945    0
946    1
947    0
948    0
949    0
Name: outcome, Length: 950, dtype: int64

In [46]:
x=pd.get_dummies(x,drop_first=True)

In [47]:
x.shape

(950, 13)

split into training and test sets

In [48]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [49]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(
x,y,test_size=0.2, random_state=42, stratify=y
)

In [50]:
x_test.shape

(190, 13)

In [51]:
x_train.shape

(760, 13)

In [52]:
print(y_train.value_counts(normalize=True))
print(y_test.value_counts(normalize=True))

outcome
0    0.713158
1    0.286842
Name: proportion, dtype: float64
outcome
0    0.710526
1    0.289474
Name: proportion, dtype: float64


## building the baseline

import your model and scaler

In [53]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

scale your features

In [54]:
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [55]:
x_test_scaled

array([[-0.40233827,  0.41776224,  0.71780533, ..., -0.19557956,
        -0.62605223, -0.72956019],
       [-1.3101938 ,  0.04023632, -1.57964332, ..., -0.19557956,
         1.59731082, -0.72956019],
       [-1.65063962,  1.55034   ,  0.54107851, ..., -0.19557956,
        -0.62605223, -0.72956019],
       ...,
       [-0.57256119, -0.71481553,  0.43504242, ..., -0.19557956,
        -0.62605223, -0.72956019],
       [ 1.07292695, -0.71481553,  2.55576425, ..., -0.19557956,
        -0.62605223, -0.72956019],
       [-0.51582022, -0.71481553,  0.18762487, ..., -0.19557956,
        -0.62605223,  1.37068883]], shape=(190, 13))

Fill the baseline model

In [56]:
model = LogisticRegression(max_iter=1000)
model.fit(x_train_scaled,y_train)

,"max_iter max_iter: int, default=100Maximum number of iterations taken for the solvers to converge.",1000
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is '

In [57]:
y_pred = model.predict(x_train_scaled)
y_pred[:10]

array([0, 0, 0, 0, 1, 0, 0, 1, 1, 0])

In [58]:
 y_pred = model.predict(x_test_scaled)
 pd.DataFrame({"actual": y_test.values[:10],
             "preducted": y_pred[:10]})

,actual,preducted
0,0,0
1,0,0
2,0,0
3,0,0
4,1,0
5,0,0
6,0,0
7,1,0
8,0,0
9,0,0


compute test accuracy

In [59]:
from sklearn.metrics import accuracy_score

test_acc =accuracy_score(y_test,y_pred)

check for overfitting

In [60]:
train_acc = accuracy_score(y_train,(model.predict(x_train_scaled)))
print("train accuracy",train_acc,"test acc",test_acc,"")
print()
print("differents between :",round(train_acc - test_acc))

train accuracy 0.7394736842105263 test acc 0.7526315789473684 

differents between : 0


read the model of coefficient

In [61]:
coefs = pd.Series(model.coef_[0], index=x.columns)
coefs.abs().sort_values(ascending=False)

glucose                         0.733848
age                             0.491292
diabetes_pedigree               0.315200
bmi_category_obese              0.229525
glucose_category_normal         0.185230
insulin                         0.145458
blood_pressure                  0.079047
bmi_category_underweight        0.068681
pregnancies                     0.038351
glucose_category_prediabetic    0.026716
bmi                             0.013643
bmi_category_overweight         0.012534
skin_thickness                  0.008147
dtype: float64

In [62]:
ranked = coefs.reindex(coefs.abs().sort_values(ascending=False).index)
ranked.round(4)

glucose                         0.7338
age                             0.4913
diabetes_pedigree               0.3152
bmi_category_obese              0.2295
glucose_category_normal        -0.1852
insulin                         0.1455
blood_pressure                 -0.0790
bmi_category_underweight       -0.0687
pregnancies                     0.0384
glucose_category_prediabetic    0.0267
bmi                             0.0136
bmi_category_overweight        -0.0125
skin_thickness                  0.0081
dtype: float64

look at probabilities behind the prediction

In [63]:
probs= model.predict_proba(x_test_scaled)
probs[:10].round(3)

array([[0.711, 0.289],
       [0.968, 0.032],
       [0.818, 0.182],
       [0.818, 0.182],
       [0.823, 0.177],
       [0.839, 0.161],
       [0.581, 0.419],
       [0.527, 0.473],
       [0.714, 0.286],
       [0.879, 0.121]])

In [64]:
probs= model.predict_proba(x_test_scaled)[:,1]
probs[:10].round(3)

array([0.289, 0.032, 0.182, 0.182, 0.177, 0.161, 0.419, 0.473, 0.286,
       0.121])

## EVALUATION FRAMEWORK

BUILD THE CONFUSION MATRIX

In [65]:
from sklearn.metrics import confusion_matrix 
confusion_matrix(y_test, y_pred)

array([[127,   8],
       [ 39,  16]])

In [66]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
tn, fp, fn, tp = cm.ravel()
print()
print(" True Negative:",tn)
print(" False Positive:",fp)
print(" False Negative:",fn)
print(" True Positive:",tp)


[[127   8]
 [ 39  16]]

 True Negative: 127
 False Positive: 8
 False Negative: 39
 True Positive: 16


In [67]:
#|cell| count|what it means for real patients|
#|True Negative|127|The model correctly predicted that 127 patients do not have diabetes.|
#|False Positive|8|The model incorrectly predicted that 8 patients have diabetes when they do not.|
#|False Negative|39|The model incorrectly predicted that 39 patients do not have diabetes when they actually do.|
#|True Positive|16|The model correctly predicted that 16 patients have diabetes.|

In [68]:
missed_rate=fn/(fn+tp)
print("Diabetic patients in the test set: " ,fn+tp)
print("found by model:",tp)
print("missed by model",fn)
print("proportion missed:",round(missed_rate,4))

Diabetic patients in the test set:  55
found by model: 16
missed by model 39
proportion missed: 0.7091


write a resuable evaluation function

In [76]:
def evaluate_model(name,model,x_test,y_test):
    y_pred = model.predict(x_test)
    acc = accuracy_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)
    tn, fn, fn ,tp =cm.ravel()

    print(name)
    print(" accuraccy :",round(acc, 4))
    print("  confusion matrix:", cm.tolist())
    print("  diabetics found:",tp,"of",tp + fn )
    print("  missed:"        ,fn)

    return{"model":name,"accuracy":round(acc,4),
           "found":tp,"missed":fn}

In [77]:
baseline_result = evaluate_model(
    "LogisticRegression (baseline)", model,x_test_scaled,y_test)

LogisticRegression (baseline)
 accuraccy : 0.7526
  confusion matrix: [[127, 8], [39, 16]]
  diabetics found: 16 of 55
  missed: 39
